# Generated by Django 3.2 on 2021-12-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RW14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_rw', models.CharField(max_length=50)),
                ('nama_ketua_rw', models.CharField(max_length=50)),
                ('alamat_rw', models.CharField(max_length=100)),
                ('hp', models.CharField(blank=True, max_length=20, null=True)),
                ('telpon', models.CharField(blank=True, max_length=20, null=True)),
                ('desa', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='desa.desa')),
            ],
            options={
                'verbose_name': 'RW 14',
                'verbose_name_plural': 'RW 14',
            },
        ),
    ]
