# Generated by Django 3.2 on 2021-12-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_desa', models.CharField(max_length=50)),
                ('nama_kades', models.CharField(max_length=50)),
                ('alamat_desa', models.CharField(max_length=100)),
                ('hp', models.CharField(blank=True, max_length=20, null=True)),
                ('telpon', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Desa',
                'verbose_name_plural': 'Desa',
            },
        ),
    ]
